#!/usr/bin/perl

use HTML::Template;
use CGI qw/:standard/;

my $routing;
my @params = split(/\//,$ENV{'PATH_INFO'});
$routing = "/".$params[1];

my $path_prefix;
my $title;
my $body;


if ($routing eq "/"){
   $path_prefix = "../";
   $title = "Hubot Maker :: hubot list";
   $body = HTML::Template->new(filename => '/var/www/haas-front/list.tmpl',
                                  'die_on_bad_params' => 0
                                  );
}elsif ($routing eq "/login"){
   $path_prefix = "../../";
   $title = "Hubot Maker :: User Login";
   $body = HTML::Template->new(filename => '/var/www/haas-front/login.tmpl',
                                  'die_on_bad_params' => 0
                                  );
}elsif ($routing eq "/register"){
   $path_prefix = "../../";
   $title = "Hubot Maker :: Registeration";
   $body = HTML::Template->new(filename => '/var/www/haas-front/register.tmpl',
                                  'die_on_bad_params' => 0
                                  );
}else{

}

my $html_1 = HTML::Template->new(filename => '/var/www/haas-front/html_1.tmpl',
                                'die_on_bad_params' => 0
                                );
my $head = HTML::Template->new(filename => '/var/www/haas-front/head.tmpl',
                                'die_on_bad_params' => 0
                                );
my $navbar = HTML::Template->new(filename => '/var/www/haas-front/navbar.tmpl',
                                'die_on_bad_params' => 0
                                );


                                $head->param(PATH_PREFIX => $path_prefix);
                                $head->param(TITLE => $title);
                                $body->param(PATH_PREFIX => $path_prefix);


print header(-type => "text/html",
             -status => 200,
    	 -charset=>'utf-8',
    	 -Access_Control_Allow_Origin=>'*');
    print  $html_1->output;
    print  $head->output;
    print  $navbar->output;
    print  $body->output;
      print "routing:".$routing;
